# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
  - echo "build start..."
  - if [ -d build ]; then rm -rf build; fi
   
stages:
  - build
  - test
   
build:
  stage: build
  script:
    - mkdir -p build && cd build
    - cmake ..
    - make
   
test:
  stage: test
  script: 
    - mkdir -p build && cd build
    - cmake ..
    - make
    - ./test/unitTest
    - if [ "$?" == 0 ]; then echo "Success"; else echo "Failed"; fi
    - cd .. && if [ -d build ]; then rm -rf build; fi
